### PR TITLE
fix(molecule): Parse hydration notation successfully

### LINKED ISSUE #12: Add hydration to molecules
At this point, strings such as `CuSO4.5H2O` will error. It would be nice if molecules could contain water molecules.

### PR DESCRIPTION
**Pull request by tommilligan**
Add macro and parsing logic to ignore separators in molecule notation such as `.` for hydration.

I've also updated the build to bring it up to date - happy to split this out as a separate PR if needed.
- `.travis.yml`
- `clippy.sh`
- `precommit.sh`

Nice work on this project! Can I ask what it was that made you start it - just interest in Rust/Chemistry, or an actual use case?

Closes #12

### CODE REVIEW

**Comment by C-Bouthoorn** [comment]
Hey, thanks a ton! I'll have to say I kind of forgot I still had this repo, so it's nice to see it somewhat active again (how did you even find it?) :laughing:  It started as in interest in Rust and needing a fun project to try it out on. At the same time, I was fiddling around with other simulation tools such as Yenka Chemistry whose license didn't allow me to use it in the weekends, so I decided to give it a try at rebuilding something similar from scratch.

That aside, I'll review your changes soon(TM), since it seems you changed quite a lot.

**Comment by tommilligan** [comment]
Ah interesting. The actual core change is a tiny one - https://github.com/feroxide/feroxide/pull/14/commits/e78ac0bad90019e38c8e1efa694a7eff96e73cc4 - the rest are fixing the build system, updating the docs, etc.

**Comment by tommilligan** [comment]
@C-Bouthoorn ping

**Comment by C-Bouthoorn** [comment]
Whoops, was kinda busy with life. Thanks a ton for your commit, it looks awesome :)

**Pull request merged**
